### ISSUE TITLE
Cobra forma de pagamento ao sair da primeira vez

### ISSUE THREAD

**Issue by diego-rapoport** [Leo-NP/projetoCaixaRegistradoraSimples#1]
Quando seleciona a opção `0` logo da primeira vez ainda assim a caixa pede a forma de pagamento, mesmo não tendo nada.

![image](https://github.com/Leo-NP/projetoCaixaRegistradoraSimples/assets/66575787/9a35b5f6-210f-4493-b2b5-6a9aa8378ac2)

**Comment by Leo-NP** [comment]
Finalizado.
